<a href="https://colab.research.google.com/github/JunaidRaza78/RI-Software-Predictive-models/blob/main/Copy_of_Product_Service_Performance_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Product and Service Performance**

Analyze best and worst performing service and product

Factors behind the performance of product and services

In [ ]:
pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.10/dist-packages (21.0.0)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)

In [ ]:
import pandas as pd
import numpy as np
from faker import Faker
import random

# Create a Faker instance
fake = Faker()

# Set seed for reproducibility
random.seed(42)

# Function to generate random barcode
def generate_barcode():
    return ''.join(random.choice('0123456789') for i in range(12))

# Function to generate mock product data
def generate_mock_product_data(num_records, num_months):
    data = {
        'id': list(range(1, num_records + 1)),
        'minimal_amount': [random.randint(1, 10) for _ in range(num_records)],
        'price': [round(random.uniform(10, 1000), 2) for _ in range(num_records)],
        'name': [fake.word() for _ in range(num_records)],
        'avatar': [None] * num_records,
        'company_id': [random.choice([1, 2, 3]) for _ in range(num_records)],
        'relationship_id': [random.choice([1, 2, 3]) for _ in range(num_records)],
        'description': [fake.text() for _ in range(num_records)],
        'barcode': [generate_barcode() for _ in range(num_records)],
        'currency': [random.choice(['USD', 'EUR', 'UAH']) for _ in range(num_records)],
        'sales': [random.randint(50, 500) for _ in range(num_records)],
        'rating': [random.uniform(1, 5) for _ in range(num_records)],
        'Month': np.tile(np.arange(1, num_months + 1), int(np.ceil(num_records / num_months)))[:num_records],
    }
    return pd.DataFrame(data)

# Function to generate mock service data
def generate_mock_service_data(num_records, num_months):
    data = {
        'id': list(range(1, num_records + 1)),
        'company_id': [random.choice([1, 2, 3]) for _ in range(num_records)],
        'relationship_id': [random.choice([1, 2, 3]) for _ in range(num_records)],
        'avatar': [None] * num_records,
        'name': [fake.word() for _ in range(num_records)],
        'price': [round(random.uniform(10, 1000), 2) for _ in range(num_records)],
        'description': [fake.text() for _ in range(num_records)],
        'barcode': [generate_barcode() for _ in range(num_records)],
        'currency': [random.choice(['USD', 'EUR', 'UAH']) for _ in range(num_records)],
        'sales': [random.randint(50, 500) for _ in range(num_records)],
        'rating': [random.uniform(1, 5) for _ in range(num_records)],
        'Month': np.tile(np.arange(1, num_months + 1), int(np.ceil(num_records / num_months)))[:num_records],
    }
    return pd.DataFrame(data)

# Generate mock product and service data
num_product_records = 100
num_service_records = 100
num_months = 12

products_df = generate_mock_product_data(num_product_records, num_months)
services_df = generate_mock_service_data(num_service_records, num_months)

products_df.head()

,id,minimal_amount,price,name,avatar,company_id,relationship_id,description,barcode,currency,sales,rating,Month
0,1,2,254.16,enjoy,None,2,2,Continue civil expert.\nTake far store entire....,158692322602,EUR,307,3.386956,1
1,2,1,565.75,sit,None,3,1,Animal happy last that situation. Too recently...,563421607337,USD,320,1.065741,2
2,3,5,270.11,speech,None,1,2,Health also measure top avoid. Same sense smal...,543303654145,UAH,264,3.061503,3
3,4,4,588.74,study,None,3,2,Management month magazine modern amount home b...,868501429401,UAH,132,1.967753,4
4,5,4,898.84,stage,None,3,1,Call current student peace. Soon during federa...,965569816934,EUR,468,1.574307,5

In [ ]:
services_df.head()

,id,company_id,relationship_id,avatar,name,price,description,barcode,currency,sales,rating,Month
0,1,3,2,None,administration,249.32,Rather nature action decision guy power.\nEnd ...,756263689702,USD,389,2.035283,1
1,2,2,3,None,able,131.30,Study air each professor person media. Exist w...,838578652785,USD,116,4.250988,2
2,3,2,3,None,add,455.10,Over test number consumer another success afte...,854973348434,USD,171,1.087201,3
3,4,2,2,None,hard,149.47,Little run strategy huge course work. Politics...,437575844198,UAH,199,1.257888,4
4,5,3,1,None,style,60.10,School right prove gun something court.\nPhone...,665240415747,UAH,183,4.609984,5

In [ ]:
def analyze_product_performance(product_data):
    """
    Analyze the performance of a product.

    Parameters:
    - product_data: DataFrame containing data for a single product.

    Returns:
    - None (prints analysis results).
    """

    # Calculate key performance indicators
    total_sales = product_data['sales'].sum()
    average_price = product_data['price'].mean()
    total_revenue = total_sales * average_price
    satisfaction_score = product_data['rating'].mean()

    # Print analysis results
    print(f"Product Analysis for {product_data['name'].iloc[0]} (Product ID: {product_data['id'].iloc[0]})")
    print("------------------------------------------")
    print(f"Total Sales: {total_sales}")
    print(f"Average Price: {average_price:.2f}")
    print(f"Total Revenue: {total_revenue:.2f}")
    print(f"Average Satisfaction Score: {satisfaction_score:.2f}")

analyze_product_performance(products_df)

Product Analysis for the (Product ID: 1)
------------------------------------------
Total Sales: 26285
Average Price: 489.17
Total Revenue: 12857849.22
Average Satisfaction Score: 3.06

In [ ]:
def find_best_performing_product(all_products_data):
    """
    Find the best-performing product based on total revenue.

    Parameters:
    - all_products_data: DataFrame containing data for all products.

    Returns:
    - DataFrame with information about the best-performing product.
    """

    # Calculate total revenue for each product
    all_products_data['TotalRevenue'] = all_products_data['sales'] * all_products_data['price']

    # Find the product with the highest total revenue
    best_product = all_products_data.loc[all_products_data['TotalRevenue'].idxmax()]

    return best_product


best_performing_product = find_best_performing_product(products_df)

# Print information about the best-performing product
print("Best Performing Product:")
print(best_performing_product)
#df_dict = best_performing_product.to_dict(orient='records')

# Display the dictionary
#print(df_dict)

Best Performing Product:
id                                                                20
minimal_amount                                                     9
price                                                         971.37
name                                                            skin
avatar                                                          None
company_id                                                         1
relationship_id                                                    3
description        Feel lose analysis claim increase. Security tr...
barcode                                                 720465375564
currency                                                         UAH
sales                                                            483
rating                                                      3.542683
TotalRevenue                                               469171.71
Name: 19, dtype: object

In [ ]:
def find_worst_performing_product(all_products_data):
    """
    Find the worst-performing product based on total revenue.

    Parameters:
    - all_products_data: DataFrame containing data for all products.

    Returns:
    - DataFrame with information about the worst-performing product.
    """

    # Calculate total revenue for each product
    all_products_data['TotalRevenue'] = all_products_data['sales'] * all_products_data['price']

    # Find the product with the lowest total revenue
    worst_product = all_products_data.loc[all_products_data['TotalRevenue'].idxmin()]

    return worst_product

worst_performing_product = find_worst_performing_product(products_df)

# Print information about the worst-performing product
print("Worst Performing Product:")
worst_performing_product

Worst Performing Product:

id                                                                46
minimal_amount                                                     9
price                                                          10.57
name                                                            well
avatar                                                          None
company_id                                                         2
relationship_id                                                    3
description        Bill talk set apply forget. Door night usually...
barcode                                                 154516808760
currency                                                         EUR
sales                                                            247
rating                                                      1.167624
TotalRevenue                                                 2610.79
Name: 45, dtype: object

In [ ]:
def analyze_performance_factors(product_data, performance_type='high'):
    """
    Analyze factors contributing to the performance of a product.

    Parameters:
    - product_data: DataFrame containing data for a single product.
    - performance_type: 'high' or 'low' to specify whether to analyze high or low-performing product.

    Returns:
    - DataFrame with information about the factors contributing to performance.
    """

    # Sort product data based on total revenue
    sorted_product_data = product_data.sort_values(by='TotalRevenue', ascending=(performance_type == 'low'))

    # Select the top-performing or bottom-performing product
    selected_product = sorted_product_data.iloc[0]

    # Extract factors contributing to performance
    factors_contributing = {
        'ProductID': selected_product['id'],
        'Name': selected_product['name'],
        'TotalRevenue': selected_product['TotalRevenue'],
        'Sales': selected_product['sales'],
        'Price': selected_product['price'],
        'rating': selected_product['rating']
    }

    return factors_contributing

high_performance_factors = analyze_performance_factors(products_df, performance_type='high')
low_performance_factors = analyze_performance_factors(products_df, performance_type='low')

# Print information about factors contributing to high-performing product
print("Factors Contributing to High-Performing Product:")
print(high_performance_factors)

# Print information about factors contributing to low-performing product
print("\nFactors Contributing to Low-Performing Product:")
print(low_performance_factors)

Factors Contributing to High-Performing Product:
{'ProductID': 20, 'Name': 'skin', 'TotalRevenue': 469171.71, 'Sales': 483, 'Price': 971.37, 'rating': 3.54268316587452}

Factors Contributing to Low-Performing Product:
{'ProductID': 46, 'Name': 'well', 'TotalRevenue': 2610.79, 'Sales': 247, 'Price': 10.57, 'rating': 1.167623767721528}

In [ ]:
def increase_sales_strategy(product_data):
    """
    Implement strategies to increase the sales of a product.

    Parameters:
    - product_data: DataFrame containing data for a single product.

    Returns:
    - List of recommendations to improve sales.
    """

    # Recommendations list
    recommendations = []

    # Check if sales are below a certain threshold
    if product_data['sales'].mean() < 100:
        recommendations.append("Launch targeted marketing campaigns to increase product visibility.")

    # Check if satisfaction score is below a certain threshold
    if product_data['rating'].mean() < 0.7:
        recommendations.append("Gather customer feedback to identify areas for product improvement.")

    # Check if the price is too high compared to competitors
    if product_data['price'].mean() > 200:
        recommendations.append("Consider price adjustments to remain competitive.")

    # Add more conditions and recommendations based on your analysis

    return recommendations

sales_recommendations = increase_sales_strategy(products_df)

# Print sales recommendations
print("Sales Recommendations:")
for recommendation in sales_recommendations:
    print(f"- {recommendation}")

Sales Recommendations:
- Consider price adjustments to remain competitive.

In [ ]:
def analyze_service_performance(service_data):
    """
    Analyze the performance of a service.

    Parameters:
    - service_data: DataFrame containing data for a single service.

    Returns:
    - None (prints analysis results).
    """

    # Calculate key performance indicators
    total_sales = service_data['sales'].sum()
    average_price = service_data['price'].mean()
    total_revenue = total_sales * average_price
    satisfaction_score = service_data['rating'].mean()

    # Print analysis results
    print(f"Service Analysis for {service_data['name'].iloc[0]} (Service ID: {service_data['id'].iloc[0]})")
    print("------------------------------------------")
    print(f"Total Sales: {total_sales}")
    print(f"Average Price: {average_price:.2f}")
    print(f"Total Revenue: {total_revenue:.2f}")
    print(f"Average Satisfaction Score: {satisfaction_score}")

analyze_service_performance(services_df)

Service Analysis for serve (Service ID: 1)
------------------------------------------
Total Sales: 26606
Average Price: 473.51
Total Revenue: 12598297.52
Average Satisfaction Score: 3.0216548948782544

In [ ]:
def find_best_performing_service(all_services_data):
    """
    Find the best-performing service based on total revenue.

    Parameters:
    - all_services_data: DataFrame containing data for all services.

    Returns:
    - DataFrame with information about the best-performing service.
    """

    # Calculate total revenue for each service
    all_services_data['TotalRevenue'] = all_services_data['sales'] * all_services_data['price']

    # Find the service with the highest total revenue
    best_service = all_services_data.loc[all_services_data['TotalRevenue'].idxmax()]

    return best_service

best_performing_service = find_best_performing_service(services_df)

# Print information about the best-performing service
print("Best Performing Service:")
print(best_performing_service)

Best Performing Service:
id                                                                87
company_id                                                         2
relationship_id                                                    3
avatar                                                          None
name                                                         someone
price                                                         972.34
description        Several generation stage music school myself b...
barcode                                                 111554262218
currency                                                         EUR
sales                                                            475
rating                                                       1.36103
TotalRevenue                                                461861.5
Name: 86, dtype: object

In [ ]:
def find_worst_performing_service(all_services_data):
    """
    Find the worst-performing service based on total revenue.

    Parameters:
    - all_services_data: DataFrame containing data for all services.

    Returns:
    - DataFrame with information about the worst-performing service.
    """

    # Calculate total revenue for each service
    all_services_data['TotalRevenue'] = all_services_data['sales'] * all_services_data['price']

    # Find the service with the lowest total revenue
    worst_service = all_services_data.loc[all_services_data['TotalRevenue'].idxmin()]

    return worst_service

worst_performing_service = find_worst_performing_service(services_df)

# Print information about the worst-performing service
print("Worst Performing Service:")
print(worst_performing_service)

Worst Performing Service:
id                                                       58
company_id                                                3
relationship_id                                           3
avatar                                                 None
name                                                  value
price                                                 48.52
description        College whether sit personal six person.
barcode                                        374167243426
currency                                                UAH
sales                                                    96
rating                                             1.400537
TotalRevenue                                        4657.92
Name: 57, dtype: object

In [ ]:
def analyze_performance_factors_service(service_data, performance_type='high'):
    """
    Analyze factors contributing to the performance of a service.

    Parameters:
    - service_data: DataFrame containing data for a single service.
    - performance_type: 'high' or 'low' to specify whether to analyze high or low-performing service.

    Returns:
    - DataFrame with information about the factors contributing to performance.
    """

    # Sort service data based on total revenue
    sorted_service_data = service_data.sort_values(by='TotalRevenue', ascending=(performance_type == 'low'))

    # Select the top-performing or bottom-performing service
    selected_service = sorted_service_data.iloc[0]

    # Extract factors contributing to performance
    factors_contributing = {
        'ServiceID': selected_service['id'],
        'Name': selected_service['name'],
        'TotalRevenue': selected_service['TotalRevenue'],
        'Sales': selected_service['sales'],
        'Price': selected_service['price'],
        'rating': selected_service['rating']
    }

    return factors_contributing

high_performance_factors_service = analyze_performance_factors_service(services_df, performance_type='high')
low_performance_factors_service = analyze_performance_factors_service(services_df, performance_type='low')

# Print information about factors contributing to high-performing service
print("Factors Contributing to High-Performing Service:")
print(high_performance_factors_service)

# Print information about factors contributing to low-performing service
print("\nFactors Contributing to Low-Performing Service:")
print(low_performance_factors_service)

Factors Contributing to High-Performing Service:
{'ServiceID': 87, 'Name': 'someone', 'TotalRevenue': 461861.5, 'Sales': 475, 'Price': 972.34, 'rating': 1.3610295074036114}

Factors Contributing to Low-Performing Service:
{'ServiceID': 58, 'Name': 'value', 'TotalRevenue': 4657.92, 'Sales': 96, 'Price': 48.52, 'rating': 1.4005373492198303}

In [ ]:
def increase_sales_strategy_service(service_data):
    """
    Implement strategies to increase the sales of a service.

    Parameters:
    - service_data: DataFrame containing data for a single service.

    Returns:
    - List of recommendations to improve sales.
    """

    # Recommendations list
    recommendations = []

    # Check if sales are below a certain threshold
    if service_data['sales'].mean() < 50:
        recommendations.append("Launch targeted marketing campaigns to increase service visibility.")

    # Check if satisfaction score is below a certain threshold
    if service_data['rating'].mean() < 0.7:
        recommendations.append("Gather customer feedback to identify areas for service improvement.")

    # Check if the price is too high compared to competitors
    if service_data['price'].mean() > 150:
        recommendations.append("Consider price adjustments to remain competitive.")

    # Add more conditions and recommendations based on your analysis

    return recommendations


sales_recommendations_service = increase_sales_strategy_service(services_df)

# Print sales recommendations for services
print("Sales Recommendations for Service:")
for recommendation in sales_recommendations_service:
    print(f"- {recommendation}")

Sales Recommendations for Service:
- Consider price adjustments to remain competitive.

In [ ]:
def find_best_company(services_df):
    """
    Find the best company based on total revenue.

    Parameters:
    - all_companies_data: DataFrame containing data for all companies.

    Returns:
    - DataFrame with information about the best-performing company.
    """

    # Calculate total revenue for each company
    services_df['TotalRevenue'] = services_df['sales'] * services_df['price']

    # Find the company with the highest total revenue
    best_company = services_df.loc[services_df['TotalRevenue'].idxmax()]

    return best_company

best_company = find_best_company(services_df)

# Print information about the best company
print("Best Company:")
print(best_company)

Best Company:
id                                                                87
company_id                                                         2
relationship_id                                                    3
avatar                                                          None
name                                                         someone
price                                                         972.34
description        Several generation stage music school myself b...
barcode                                                 111554262218
currency                                                         EUR
sales                                                            475
rating                                                       1.36103
TotalRevenue                                                461861.5
Name: 86, dtype: object

In [ ]:
def find_worst_company(services_df):
    """
    Find the best company based on total revenue.

    Parameters:
    - all_companies_data: DataFrame containing data for all companies.

    Returns:
    - DataFrame with information about the best-performing company.
    """

    # Calculate total revenue for each company
    services_df['TotalRevenue'] = services_df['sales'] * services_df['price']

    # Find the company with the highest total revenue
    worst_company = services_df.loc[services_df['TotalRevenue'].idxmin()]

    return worst_company

worst_company = find_worst_company(services_df)

# Print information about the best company
print("Worst Company:")
print(worst_company)

Worst Company:
id                                                       58
company_id                                                3
relationship_id                                           3
avatar                                                 None
name                                                  value
price                                                 48.52
description        College whether sit personal six person.
barcode                                        374167243426
currency                                                UAH
sales                                                    96
rating                                             1.400537
TotalRevenue                                        4657.92
Name: 57, dtype: object

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Product_ID_{product_id}_rating'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'Time': row['Month'],
                'Rating': row['rating'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(products_df)
print(product_performance_dict)

{'Product_ID_1_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 3.386956171275788}], 'Product_ID_2_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 1.0657414088235777}], 'Product_ID_3_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 3.0615029208376243}], 'Product_ID_4_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 1.9677525376839733}], 'Product_ID_5_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 1.5743073609850402}], 'Product_ID_6_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.716955572413335}], 'Product_ID_7_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 3.4592383311038026}], 'Product_ID_8_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 1.9622569552261742}], 'Product_ID_9_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 2.6662703808341592}], 'Product_ID_10_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 3.6574852069680364}], 'Product_ID_11_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 1.342455819949047}], 'Product_ID_12_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 4.898617963808887}], 'Product_ID_13_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 1.2707172916353842}], 'Product_ID_14_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 3.104237781288682}], 'Product_ID_15_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 3.0293107863191464}], 'Product_ID_16_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 4.95332594238587}], 'Product_ID_17_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 3.216607809672782}], 'Product_ID_18_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.5618149302402564}], 'Product_ID_19_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 2.880540312633944}], 'Product_ID_20_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 3.54268316587452}], 'Product_ID_21_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 4.924157690206242}], 'Product_ID_22_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 2.014601044276851}], 'Product_ID_23_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 1.0649689244357905}], 'Product_ID_24_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 4.154080065118061}], 'Product_ID_25_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 2.379209972653565}], 'Product_ID_26_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 3.9317640858025666}], 'Product_ID_27_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 3.5130278499026257}], 'Product_ID_28_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 4.086005496439436}], 'Product_ID_29_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 3.940747939249245}], 'Product_ID_30_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.3300744334879395}], 'Product_ID_31_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 1.1773427531808327}], 'Product_ID_32_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 3.184054980830766}], 'Product_ID_33_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 4.254035462224353}], 'Product_ID_34_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 1.7003565082068337}], 'Product_ID_35_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 4.116570373913126}], 'Product_ID_36_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 2.858491598988151}], 'Product_ID_37_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 3.7815570079842558}], 'Product_ID_38_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 3.526943391033351}], 'Product_ID_39_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 4.245990727390426}], 'Product_ID_40_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 1.2524021481288985}], 'Product_ID_41_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 4.1047615988136865}], 'Product_ID_42_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.830718309789413}], 'Product_ID_43_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 2.173770284700125}], 'Product_ID_44_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 1.1752251026364924}], 'Product_ID_45_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 1.7978793348607534}], 'Product_ID_46_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 1.167623767721528}], 'Product_ID_47_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 4.733483919801589}], 'Product_ID_48_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 3.061534357017995}], 'Product_ID_49_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 4.956490809184494}], 'Product_ID_50_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 3.1721227906167435}], 'Product_ID_51_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 2.0132550608104696}], 'Product_ID_52_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 4.013163675275459}], 'Product_ID_53_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 1.7644137229356436}], 'Product_ID_54_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.4278967041414536}], 'Product_ID_55_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 4.1233662679137}], 'Product_ID_56_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 4.463193108312231}], 'Product_ID_57_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 2.327698745525378}], 'Product_ID_58_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 1.4979000329775336}], 'Product_ID_59_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 2.472076697258692}], 'Product_ID_60_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 4.557946068049126}], 'Product_ID_61_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 3.973230822078485}], 'Product_ID_62_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 4.578549979820213}], 'Product_ID_63_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 2.5465790730427686}], 'Product_ID_64_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 4.894894337261237}], 'Product_ID_65_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 2.9848129061480906}], 'Product_ID_66_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.9900935699745093}], 'Product_ID_67_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 4.697241866507854}], 'Product_ID_68_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 3.077103414139768}], 'Product_ID_69_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 4.204592349607095}], 'Product_ID_70_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 3.908325297370543}], 'Product_ID_71_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 1.3157080242218715}], 'Product_ID_72_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 3.409813195320909}], 'Product_ID_73_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 4.289365118159546}], 'Product_ID_74_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 3.181897589378548}], 'Product_ID_75_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 2.284845712858376}], 'Product_ID_76_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 1.320275644299981}], 'Product_ID_77_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 3.6436768858325466}], 'Product_ID_78_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 2.22598342436301}], 'Product_ID_79_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 3.410486510922399}], 'Product_ID_80_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 2.7044642915321817}], 'Product_ID_81_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 3.759059233781945}], 'Product_ID_82_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 2.4061879350879685}], 'Product_ID_83_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 1.169420651400518}], 'Product_ID_84_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 4.480148700225568}], 'Product_ID_85_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 2.4102372412339292}], 'Product_ID_86_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 4.992602391092197}], 'Product_ID_87_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 2.0982214402994304}], 'Product_ID_88_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 4.920109116777116}], 'Product_ID_89_rating': [{'Time': Timestamp('1900-05-01 00:00:00'), 'Rating': 4.791617514412345}], 'Product_ID_90_rating': [{'Time': Timestamp('1900-06-01 00:00:00'), 'Rating': 1.300164659952637}], 'Product_ID_91_rating': [{'Time': Timestamp('1900-07-01 00:00:00'), 'Rating': 3.5500501515331933}], 'Product_ID_92_rating': [{'Time': Timestamp('1900-08-01 00:00:00'), 'Rating': 2.4532445226039292}], 'Product_ID_93_rating': [{'Time': Timestamp('1900-09-01 00:00:00'), 'Rating': 4.204383902248679}], 'Product_ID_94_rating': [{'Time': Timestamp('1900-10-01 00:00:00'), 'Rating': 3.7176424312587595}], 'Product_ID_95_rating': [{'Time': Timestamp('1900-11-01 00:00:00'), 'Rating': 4.811157585118432}], 'Product_ID_96_rating': [{'Time': Timestamp('1900-12-01 00:00:00'), 'Rating': 1.571117873450199}], 'Product_ID_97_rating': [{'Time': Timestamp('1900-01-01 00:00:00'), 'Rating': 3.4302916132834214}], 'Product_ID_98_rating': [{'Time': Timestamp('1900-02-01 00:00:00'), 'Rating': 4.125247878973866}], 'Product_ID_99_rating': [{'Time': Timestamp('1900-03-01 00:00:00'), 'Rating': 1.139195863194168}], 'Product_ID_100_rating': [{'Time': Timestamp('1900-04-01 00:00:00'), 'Rating': 1.2689334522484352}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Product_ID_{product_id}_sales'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['sales'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(products_df)
print(product_performance_dict)

{'Product_ID_1_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 307}], 'Product_ID_2_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 320}], 'Product_ID_3_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 264}], 'Product_ID_4_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 132}], 'Product_ID_5_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 468}], 'Product_ID_6_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 152}], 'Product_ID_7_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 460}], 'Product_ID_8_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 359}], 'Product_ID_9_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 120}], 'Product_ID_10_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 496}], 'Product_ID_11_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 178}], 'Product_ID_12_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 76}], 'Product_ID_13_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 378}], 'Product_ID_14_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 296}], 'Product_ID_15_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 497}], 'Product_ID_16_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 240}], 'Product_ID_17_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 333}], 'Product_ID_18_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 102}], 'Product_ID_19_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 414}], 'Product_ID_20_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 483}], 'Product_ID_21_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 314}], 'Product_ID_22_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 485}], 'Product_ID_23_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 113}], 'Product_ID_24_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 195}], 'Product_ID_25_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 92}], 'Product_ID_26_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 440}], 'Product_ID_27_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 132}], 'Product_ID_28_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 189}], 'Product_ID_29_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 280}], 'Product_ID_30_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 312}], 'Product_ID_31_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 125}], 'Product_ID_32_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 475}], 'Product_ID_33_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 273}], 'Product_ID_34_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 96}], 'Product_ID_35_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 163}], 'Product_ID_36_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 468}], 'Product_ID_37_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 280}], 'Product_ID_38_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 228}], 'Product_ID_39_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 63}], 'Product_ID_40_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 262}], 'Product_ID_41_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 77}], 'Product_ID_42_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 252}], 'Product_ID_43_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 307}], 'Product_ID_44_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 241}], 'Product_ID_45_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 170}], 'Product_ID_46_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 247}], 'Product_ID_47_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 91}], 'Product_ID_48_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 241}], 'Product_ID_49_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 164}], 'Product_ID_50_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 64}], 'Product_ID_51_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 213}], 'Product_ID_52_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 100}], 'Product_ID_53_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 479}], 'Product_ID_54_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 415}], 'Product_ID_55_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 382}], 'Product_ID_56_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 221}], 'Product_ID_57_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 455}], 'Product_ID_58_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 124}], 'Product_ID_59_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 120}], 'Product_ID_60_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 69}], 'Product_ID_61_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 196}], 'Product_ID_62_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 474}], 'Product_ID_63_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 291}], 'Product_ID_64_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 406}], 'Product_ID_65_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 475}], 'Product_ID_66_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 121}], 'Product_ID_67_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 438}], 'Product_ID_68_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 411}], 'Product_ID_69_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 290}], 'Product_ID_70_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 279}], 'Product_ID_71_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 365}], 'Product_ID_72_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 52}], 'Product_ID_73_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 90}], 'Product_ID_74_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 59}], 'Product_ID_75_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 181}], 'Product_ID_76_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 160}], 'Product_ID_77_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 477}], 'Product_ID_78_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 126}], 'Product_ID_79_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 330}], 'Product_ID_80_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 422}], 'Product_ID_81_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 361}], 'Product_ID_82_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 320}], 'Product_ID_83_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 266}], 'Product_ID_84_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 106}], 'Product_ID_85_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 447}], 'Product_ID_86_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 197}], 'Product_ID_87_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 171}], 'Product_ID_88_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 204}], 'Product_ID_89_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 112}], 'Product_ID_90_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 74}], 'Product_ID_91_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 172}], 'Product_ID_92_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 264}], 'Product_ID_93_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 377}], 'Product_ID_94_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 456}], 'Product_ID_95_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 368}], 'Product_ID_96_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 284}], 'Product_ID_97_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 82}], 'Product_ID_98_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 106}], 'Product_ID_99_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 478}], 'Product_ID_100_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 305}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Product_ID_{product_id}_price'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['price'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(products_df)
print(product_performance_dict)

{'Product_ID_1_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 254.16}], 'Product_ID_2_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 565.75}], 'Product_ID_3_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 270.11}], 'Product_ID_4_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 588.74}], 'Product_ID_5_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 898.84}], 'Product_ID_6_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 405.41}], 'Product_ID_7_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 227.13}], 'Product_ID_8_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 997.56}], 'Product_ID_9_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 514.43}], 'Product_ID_10_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 100.0}], 'Product_ID_11_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 56.65}], 'Product_ID_12_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 118.55}], 'Product_ID_13_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 631.17}], 'Product_ID_14_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 794.16}], 'Product_ID_15_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 427.94}], 'Product_ID_16_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 72.89}], 'Product_ID_17_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 387.8}], 'Product_ID_18_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 996.16}], 'Product_ID_19_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 533.82}], 'Product_ID_20_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 971.37}], 'Product_ID_21_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 862.17}], 'Product_ID_22_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 21.37}], 'Product_ID_23_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 723.51}], 'Product_ID_24_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 684.89}], 'Product_ID_25_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 541.6}], 'Product_ID_26_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 274.16}], 'Product_ID_27_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 644.55}], 'Product_ID_28_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 120.44}], 'Product_ID_29_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 440.42}], 'Product_ID_30_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 459.19}], 'Product_ID_31_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 954.28}], 'Product_ID_32_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 877.09}], 'Product_ID_33_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 270.76}], 'Product_ID_34_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 505.58}], 'Product_ID_35_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 186.87}], 'Product_ID_36_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 913.5}], 'Product_ID_37_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 871.81}], 'Product_ID_38_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 305.46}], 'Product_ID_39_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 642.56}], 'Product_ID_40_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 612.88}], 'Product_ID_41_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 161.31}], 'Product_ID_42_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 764.89}], 'Product_ID_43_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 543.99}], 'Product_ID_44_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 780.84}], 'Product_ID_45_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 535.05}], 'Product_ID_46_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 10.57}], 'Product_ID_47_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 330.91}], 'Product_ID_48_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 29.28}], 'Product_ID_49_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 929.81}], 'Product_ID_50_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 879.93}], 'Product_ID_51_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 833.35}], 'Product_ID_52_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 314.44}], 'Product_ID_53_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 67.35}], 'Product_ID_54_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 879.23}], 'Product_ID_55_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 947.48}], 'Product_ID_56_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 94.8}], 'Product_ID_57_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 491.13}], 'Product_ID_58_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 78.52}], 'Product_ID_59_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 763.0}], 'Product_ID_60_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 768.18}], 'Product_ID_61_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 137.11}], 'Product_ID_62_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 480.53}], 'Product_ID_63_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 554.31}], 'Product_ID_64_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 272.41}], 'Product_ID_65_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 873.71}], 'Product_ID_66_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 428.91}], 'Product_ID_67_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 219.68}], 'Product_ID_68_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 543.9}], 'Product_ID_69_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 732.63}], 'Product_ID_70_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 209.14}], 'Product_ID_71_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 318.6}], 'Product_ID_72_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 995.2}], 'Product_ID_73_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 653.38}], 'Product_ID_74_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 443.72}], 'Product_ID_75_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 522.4}], 'Product_ID_76_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 129.79}], 'Product_ID_77_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 232.45}], 'Product_ID_78_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 344.7}], 'Product_ID_79_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 592.43}], 'Product_ID_80_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 237.81}], 'Product_ID_81_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 228.02}], 'Product_ID_82_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 80.28}], 'Product_ID_83_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 634.79}], 'Product_ID_84_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 236.65}], 'Product_ID_85_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 906.37}], 'Product_ID_86_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 861.04}], 'Product_ID_87_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 80.15}], 'Product_ID_88_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 245.62}], 'Product_ID_89_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 672.29}], 'Product_ID_90_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 222.09}], 'Product_ID_91_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 140.99}], 'Product_ID_92_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 936.16}], 'Product_ID_93_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 575.33}], 'Product_ID_94_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 477.94}], 'Product_ID_95_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 786.77}], 'Product_ID_96_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 809.42}], 'Product_ID_97_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 198.51}], 'Product_ID_98_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 105.96}], 'Product_ID_99_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 436.74}], 'Product_ID_100_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 429.34}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Product_ID_{product_id}_minimal_amount'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['minimal_amount'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(products_df)
print(product_performance_dict)

{'Product_ID_1_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 2}], 'Product_ID_2_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 1}], 'Product_ID_3_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 5}], 'Product_ID_4_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 4}], 'Product_ID_5_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 4}], 'Product_ID_6_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 3}], 'Product_ID_7_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 2}], 'Product_ID_8_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 9}], 'Product_ID_9_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 2}], 'Product_ID_10_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 10}], 'Product_ID_11_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 7}], 'Product_ID_12_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 1}], 'Product_ID_13_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 1}], 'Product_ID_14_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 2}], 'Product_ID_15_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 4}], 'Product_ID_16_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 4}], 'Product_ID_17_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 9}], 'Product_ID_18_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 10}], 'Product_ID_19_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 1}], 'Product_ID_20_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 9}], 'Product_ID_21_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 4}], 'Product_ID_22_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 9}], 'Product_ID_23_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 7}], 'Product_ID_24_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 4}], 'Product_ID_25_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 8}], 'Product_ID_26_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 10}], 'Product_ID_27_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 5}], 'Product_ID_28_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 1}], 'Product_ID_29_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 3}], 'Product_ID_30_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 7}], 'Product_ID_31_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 6}], 'Product_ID_32_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 5}], 'Product_ID_33_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 3}], 'Product_ID_34_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4}], 'Product_ID_35_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 6}], 'Product_ID_36_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2}], 'Product_ID_37_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 2}], 'Product_ID_38_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 7}], 'Product_ID_39_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 2}], 'Product_ID_40_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 6}], 'Product_ID_41_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 6}], 'Product_ID_42_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 10}], 'Product_ID_43_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 5}], 'Product_ID_44_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 1}], 'Product_ID_45_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 8}], 'Product_ID_46_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 9}], 'Product_ID_47_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 2}], 'Product_ID_48_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 7}], 'Product_ID_49_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 2}], 'Product_ID_50_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 9}], 'Product_ID_51_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 5}], 'Product_ID_52_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 10}], 'Product_ID_53_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 6}], 'Product_ID_54_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 10}], 'Product_ID_55_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 4}], 'Product_ID_56_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 2}], 'Product_ID_57_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 1}], 'Product_ID_58_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4}], 'Product_ID_59_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 5}], 'Product_ID_60_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2}], 'Product_ID_61_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4}], 'Product_ID_62_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 2}], 'Product_ID_63_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 7}], 'Product_ID_64_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 5}], 'Product_ID_65_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 8}], 'Product_ID_66_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 6}], 'Product_ID_67_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 3}], 'Product_ID_68_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 6}], 'Product_ID_69_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 6}], 'Product_ID_70_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4}], 'Product_ID_71_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 5}], 'Product_ID_72_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2}], 'Product_ID_73_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 10}], 'Product_ID_74_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 3}], 'Product_ID_75_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 9}], 'Product_ID_76_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 4}], 'Product_ID_77_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 3}], 'Product_ID_78_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 8}], 'Product_ID_79_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 7}], 'Product_ID_80_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 5}], 'Product_ID_81_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 9}], 'Product_ID_82_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4}], 'Product_ID_83_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 6}], 'Product_ID_84_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 1}], 'Product_ID_85_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4}], 'Product_ID_86_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 1}], 'Product_ID_87_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 6}], 'Product_ID_88_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 7}], 'Product_ID_89_minimal_amount': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 5}], 'Product_ID_90_minimal_amount': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 2}], 'Product_ID_91_minimal_amount': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 4}], 'Product_ID_92_minimal_amount': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 10}], 'Product_ID_93_minimal_amount': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 6}], 'Product_ID_94_minimal_amount': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4}], 'Product_ID_95_minimal_amount': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 8}], 'Product_ID_96_minimal_amount': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 7}], 'Product_ID_97_minimal_amount': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 8}], 'Product_ID_98_minimal_amount': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 3}], 'Product_ID_99_minimal_amount': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 5}], 'Product_ID_100_minimal_amount': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 3}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Service_ID_{product_id}_rating'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['rating'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(services_df)
print(product_performance_dict)

{'Service_ID_1_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 2.0352826093861034}], 'Service_ID_2_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 4.250988366454457}], 'Service_ID_3_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 1.087200730954451}], 'Service_ID_4_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 1.257888144187639}], 'Service_ID_5_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 4.609984327733126}], 'Service_ID_6_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 2.7737252953439553}], 'Service_ID_7_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 1.515166195988018}], 'Service_ID_8_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 4.620311881520612}], 'Service_ID_9_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 4.317424708869671}], 'Service_ID_10_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 2.326199565009107}], 'Service_ID_11_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 1.1707852763617232}], 'Service_ID_12_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2.843979688007763}], 'Service_ID_13_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 1.6719568349162257}], 'Service_ID_14_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 3.295536799226891}], 'Service_ID_15_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 4.2867416061291355}], 'Service_ID_16_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 2.5799947528876777}], 'Service_ID_17_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 1.117929172001166}], 'Service_ID_18_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 3.7328516670067313}], 'Service_ID_19_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 1.6912288473231567}], 'Service_ID_20_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 1.8588644238801066}], 'Service_ID_21_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 1.7486044548446467}], 'Service_ID_22_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 2.1194182171228952}], 'Service_ID_23_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 4.533695195574504}], 'Service_ID_24_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 1.1385977749260237}], 'Service_ID_25_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 3.476706195383583}], 'Service_ID_26_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 1.9831391169809818}], 'Service_ID_27_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 2.180420651998866}], 'Service_ID_28_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 2.6479688251846603}], 'Service_ID_29_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 3.202754660815922}], 'Service_ID_30_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 1.243916275731371}], 'Service_ID_31_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 2.1191039497558855}], 'Service_ID_32_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 1.5489440685282592}], 'Service_ID_33_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 1.7978312266663465}], 'Service_ID_34_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4.53861006489986}], 'Service_ID_35_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 3.103256233011119}], 'Service_ID_36_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 3.5230175552990217}], 'Service_ID_37_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4.20867233108451}], 'Service_ID_38_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 4.179384977207481}], 'Service_ID_39_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 4.957614463046136}], 'Service_ID_40_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 4.1276630673817}], 'Service_ID_41_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 2.43644843935026}], 'Service_ID_42_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 3.1780712241362066}], 'Service_ID_43_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 2.9387179417620333}], 'Service_ID_44_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 4.650708066393468}], 'Service_ID_45_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 3.009573022174967}], 'Service_ID_46_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 2.5535250982772015}], 'Service_ID_47_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 1.7192634947914769}], 'Service_ID_48_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2.275510269317518}], 'Service_ID_49_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 1.8760807522923781}], 'Service_ID_50_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 4.583059126457255}], 'Service_ID_51_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 4.114153125313898}], 'Service_ID_52_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 1.234364921112474}], 'Service_ID_53_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 4.966125293722284}], 'Service_ID_54_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 3.1177291678617265}], 'Service_ID_55_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 4.0673686738010915}], 'Service_ID_56_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 4.998422987245384}], 'Service_ID_57_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 4.895919446934009}], 'Service_ID_58_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 1.4005373492198303}], 'Service_ID_59_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 3.627457685504937}], 'Service_ID_60_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2.0661080042627322}], 'Service_ID_61_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4.265140646434939}], 'Service_ID_62_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 4.669037930281762}], 'Service_ID_63_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 1.223634623409799}], 'Service_ID_64_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 4.985568194025829}], 'Service_ID_65_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 1.8776463441756994}], 'Service_ID_66_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 4.386020361860533}], 'Service_ID_67_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 4.189562749517635}], 'Service_ID_68_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 2.4192185382606395}], 'Service_ID_69_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 4.356889009223638}], 'Service_ID_70_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4.380883609465123}], 'Service_ID_71_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 1.7044014703199601}], 'Service_ID_72_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 3.370078036725651}], 'Service_ID_73_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4.224840901437553}], 'Service_ID_74_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 3.79050625439832}], 'Service_ID_75_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 4.655920016514138}], 'Service_ID_76_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 1.1128262789086363}], 'Service_ID_77_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 3.802243213405673}], 'Service_ID_78_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 4.790234940280061}], 'Service_ID_79_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 3.2544259471327748}], 'Service_ID_80_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 3.2524355634560735}], 'Service_ID_81_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 1.7529346596210251}], 'Service_ID_82_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 4.952024841618572}], 'Service_ID_83_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 4.526505439591041}], 'Service_ID_84_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 2.968906895581621}], 'Service_ID_85_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 2.2362122886048783}], 'Service_ID_86_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 2.961745680509917}], 'Service_ID_87_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 1.3610295074036114}], 'Service_ID_88_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 1.9304934323329563}], 'Service_ID_89_rating': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 1.875235766766309}], 'Service_ID_90_rating': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 3.1057940565940436}], 'Service_ID_91_rating': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 1.0027339855353232}], 'Service_ID_92_rating': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 4.671584743682586}], 'Service_ID_93_rating': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 1.8058575334085645}], 'Service_ID_94_rating': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 1.5219581824767303}], 'Service_ID_95_rating': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 3.8677505307632645}], 'Service_ID_96_rating': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 4.675123149228824}], 'Service_ID_97_rating': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 4.377136345750603}], 'Service_ID_98_rating': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 2.2943552452193487}], 'Service_ID_99_rating': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 1.0876515849742892}], 'Service_ID_100_rating': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 3.346436700364838}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Service_ID_{product_id}_price'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['price'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(services_df)
print(product_performance_dict)

{'Service_ID_1_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 249.32}], 'Service_ID_2_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 131.3}], 'Service_ID_3_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 455.1}], 'Service_ID_4_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 149.47}], 'Service_ID_5_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 60.1}], 'Service_ID_6_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 945.93}], 'Service_ID_7_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 865.52}], 'Service_ID_8_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 423.95}], 'Service_ID_9_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 963.06}], 'Service_ID_10_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 903.29}], 'Service_ID_11_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 815.34}], 'Service_ID_12_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 934.41}], 'Service_ID_13_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 723.92}], 'Service_ID_14_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 197.94}], 'Service_ID_15_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 167.75}], 'Service_ID_16_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 996.01}], 'Service_ID_17_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 472.15}], 'Service_ID_18_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 880.28}], 'Service_ID_19_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 502.4}], 'Service_ID_20_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 99.15}], 'Service_ID_21_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 399.31}], 'Service_ID_22_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 462.66}], 'Service_ID_23_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 248.32}], 'Service_ID_24_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 587.51}], 'Service_ID_25_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 58.17}], 'Service_ID_26_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 288.54}], 'Service_ID_27_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 601.54}], 'Service_ID_28_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 844.42}], 'Service_ID_29_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 675.8}], 'Service_ID_30_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 292.89}], 'Service_ID_31_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 18.1}], 'Service_ID_32_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 116.42}], 'Service_ID_33_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 142.6}], 'Service_ID_34_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 271.83}], 'Service_ID_35_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 372.12}], 'Service_ID_36_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 409.22}], 'Service_ID_37_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 54.79}], 'Service_ID_38_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 60.65}], 'Service_ID_39_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 566.2}], 'Service_ID_40_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 368.9}], 'Service_ID_41_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 295.72}], 'Service_ID_42_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 392.49}], 'Service_ID_43_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 455.85}], 'Service_ID_44_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 554.36}], 'Service_ID_45_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 827.06}], 'Service_ID_46_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 627.01}], 'Service_ID_47_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 614.93}], 'Service_ID_48_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 137.38}], 'Service_ID_49_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 105.71}], 'Service_ID_50_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 379.47}], 'Service_ID_51_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 986.92}], 'Service_ID_52_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 562.25}], 'Service_ID_53_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 371.95}], 'Service_ID_54_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 152.82}], 'Service_ID_55_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 606.44}], 'Service_ID_56_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 407.37}], 'Service_ID_57_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 49.85}], 'Service_ID_58_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 48.52}], 'Service_ID_59_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 716.46}], 'Service_ID_60_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 805.93}], 'Service_ID_61_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 524.14}], 'Service_ID_62_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 157.45}], 'Service_ID_63_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 894.2}], 'Service_ID_64_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 148.38}], 'Service_ID_65_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 932.06}], 'Service_ID_66_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 325.34}], 'Service_ID_67_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 399.03}], 'Service_ID_68_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 620.34}], 'Service_ID_69_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 844.18}], 'Service_ID_70_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 597.79}], 'Service_ID_71_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 512.24}], 'Service_ID_72_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 514.62}], 'Service_ID_73_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 494.95}], 'Service_ID_74_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 567.3}], 'Service_ID_75_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 480.14}], 'Service_ID_76_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 26.47}], 'Service_ID_77_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 337.93}], 'Service_ID_78_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 118.51}], 'Service_ID_79_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 422.37}], 'Service_ID_80_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 314.6}], 'Service_ID_81_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 899.78}], 'Service_ID_82_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 873.38}], 'Service_ID_83_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 632.97}], 'Service_ID_84_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 600.94}], 'Service_ID_85_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 272.88}], 'Service_ID_86_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 659.04}], 'Service_ID_87_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 972.34}], 'Service_ID_88_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 582.69}], 'Service_ID_89_price': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 235.27}], 'Service_ID_90_price': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 60.84}], 'Service_ID_91_price': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 485.64}], 'Service_ID_92_price': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 528.99}], 'Service_ID_93_price': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 723.97}], 'Service_ID_94_price': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 776.86}], 'Service_ID_95_price': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 386.39}], 'Service_ID_96_price': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 823.44}], 'Service_ID_97_price': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 249.77}], 'Service_ID_98_price': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 576.84}], 'Service_ID_99_price': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 703.52}], 'Service_ID_100_price': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 198.88}]}

In [ ]:
import pandas as pd

def product_performance_dict(df):
    """
    Generate a nested dictionary with product performance data for each product in the desired format.

    Parameters:
    - df: DataFrame containing mock product data with columns 'id', 'minimal_amount', 'price', 'sales', 'rating', 'Month'

    Returns:
    - product_performance_dict: Nested dictionary with product performance data for each product
    """
    # Convert 'Month' to timestamps
    df['Month'] = pd.to_datetime(df['Month'], format='%m', errors='coerce')

    # Create a nested dictionary for product performance
    product_performance_dict = {}

    for product_id, data in df.groupby('id'):
        key = f'Service_ID_{product_id}_sales'
        product_performance_dict[key] = []

        for idx, row in data.iterrows():
            product_performance_dict[key].append({
                'label': row['Month'],
                'value': row['sales'],
            })

    return product_performance_dict


product_performance_dict = product_performance_dict(services_df)
print(product_performance_dict)

{'Service_ID_1_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 389}], 'Service_ID_2_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 116}], 'Service_ID_3_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 171}], 'Service_ID_4_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 199}], 'Service_ID_5_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 183}], 'Service_ID_6_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 485}], 'Service_ID_7_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 211}], 'Service_ID_8_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 460}], 'Service_ID_9_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 251}], 'Service_ID_10_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 408}], 'Service_ID_11_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 475}], 'Service_ID_12_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 426}], 'Service_ID_13_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 217}], 'Service_ID_14_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 212}], 'Service_ID_15_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 281}], 'Service_ID_16_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 189}], 'Service_ID_17_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 169}], 'Service_ID_18_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 88}], 'Service_ID_19_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 153}], 'Service_ID_20_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 119}], 'Service_ID_21_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 449}], 'Service_ID_22_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 444}], 'Service_ID_23_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 349}], 'Service_ID_24_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 105}], 'Service_ID_25_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 129}], 'Service_ID_26_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 104}], 'Service_ID_27_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 134}], 'Service_ID_28_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 280}], 'Service_ID_29_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 288}], 'Service_ID_30_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 210}], 'Service_ID_31_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 258}], 'Service_ID_32_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 111}], 'Service_ID_33_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 324}], 'Service_ID_34_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 233}], 'Service_ID_35_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 444}], 'Service_ID_36_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 156}], 'Service_ID_37_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 281}], 'Service_ID_38_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 207}], 'Service_ID_39_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 287}], 'Service_ID_40_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 185}], 'Service_ID_41_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 486}], 'Service_ID_42_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 111}], 'Service_ID_43_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 96}], 'Service_ID_44_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 130}], 'Service_ID_45_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 463}], 'Service_ID_46_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 401}], 'Service_ID_47_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 205}], 'Service_ID_48_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 473}], 'Service_ID_49_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 410}], 'Service_ID_50_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 406}], 'Service_ID_51_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 358}], 'Service_ID_52_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 70}], 'Service_ID_53_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 160}], 'Service_ID_54_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 477}], 'Service_ID_55_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 488}], 'Service_ID_56_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 217}], 'Service_ID_57_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 125}], 'Service_ID_58_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 96}], 'Service_ID_59_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 414}], 'Service_ID_60_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 177}], 'Service_ID_61_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 232}], 'Service_ID_62_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 252}], 'Service_ID_63_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 312}], 'Service_ID_64_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 75}], 'Service_ID_65_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 396}], 'Service_ID_66_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 203}], 'Service_ID_67_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 183}], 'Service_ID_68_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 469}], 'Service_ID_69_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 139}], 'Service_ID_70_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 65}], 'Service_ID_71_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 257}], 'Service_ID_72_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 487}], 'Service_ID_73_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 281}], 'Service_ID_74_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 334}], 'Service_ID_75_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 433}], 'Service_ID_76_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 331}], 'Service_ID_77_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 177}], 'Service_ID_78_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 98}], 'Service_ID_79_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 286}], 'Service_ID_80_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 102}], 'Service_ID_81_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 461}], 'Service_ID_82_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 456}], 'Service_ID_83_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 121}], 'Service_ID_84_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 112}], 'Service_ID_85_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 56}], 'Service_ID_86_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 81}], 'Service_ID_87_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 475}], 'Service_ID_88_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 449}], 'Service_ID_89_sales': [{'label': Timestamp('1900-05-01 00:00:00'), 'value': 163}], 'Service_ID_90_sales': [{'label': Timestamp('1900-06-01 00:00:00'), 'value': 116}], 'Service_ID_91_sales': [{'label': Timestamp('1900-07-01 00:00:00'), 'value': 151}], 'Service_ID_92_sales': [{'label': Timestamp('1900-08-01 00:00:00'), 'value': 471}], 'Service_ID_93_sales': [{'label': Timestamp('1900-09-01 00:00:00'), 'value': 255}], 'Service_ID_94_sales': [{'label': Timestamp('1900-10-01 00:00:00'), 'value': 240}], 'Service_ID_95_sales': [{'label': Timestamp('1900-11-01 00:00:00'), 'value': 401}], 'Service_ID_96_sales': [{'label': Timestamp('1900-12-01 00:00:00'), 'value': 372}], 'Service_ID_97_sales': [{'label': Timestamp('1900-01-01 00:00:00'), 'value': 380}], 'Service_ID_98_sales': [{'label': Timestamp('1900-02-01 00:00:00'), 'value': 93}], 'Service_ID_99_sales': [{'label': Timestamp('1900-03-01 00:00:00'), 'value': 348}], 'Service_ID_100_sales': [{'label': Timestamp('1900-04-01 00:00:00'), 'value': 350}]}